services:
  echo-http-server:
    container_name: echo-http-server
    tty: true
    build: containers/echo-http-server
    ports:
      - "12345:12345"
  static-files-http-server:
    build: containers/nginx
    container_name: static-files-http-server
    environment:
      - FLAG=${FLAG}
    tty: true
    ports:
      - "80:80"
